import type { NextPage } from 'next'
import Head from 'next/head'
import Experience from '../components/Experience'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hobbies from '../components/Hobbies'
import Intro from '../components/Intro'
import Projects from '../components/Projects'
import styles from '../styles/home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>George Go - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <Header />
      </div>
      <div className={styles.content}>
        {/* Main page content goes here */}
        <Intro />
        <Experience />
        <Projects />
        <Hobbies />
      </div>
      <div className={styles.footer}>
        <Footer />
      </div>
    </div>
  )
}

export default Home
