import type { NextPage } from 'next'
import Head from 'next/head'
import Experience from '../components/Experience'
import FooterNav from '../components/FooterNav'
import Header from '../components/Header'
import Intro from '../components/Intro'
import Projects from '../components/Projects'
import styles from '../styles/Home.module.css'
import { ContentContext, ContentContextProps } from '../contexts/ContentContext'
import { useState } from 'react'
import About from '../components/About'

const Home: NextPage = () => {
  const [homeIsOpen, setHomeIsOpen] = useState(true);
  const [experienceIsOpen, setExperienceIsOpen] = useState(false);
  const [projectsIsOpen, setProjectsIsOpen] = useState(false);
  const [hobbiesIsOpen, setHobbiesIsOpen] = useState(false);

  const contentDefaultValues: ContentContextProps = {
    homeIsOpen: homeIsOpen,
    experienceIsOpen: experienceIsOpen,
    projectsIsOpen: projectsIsOpen,
    hobbiesIsOpen: hobbiesIsOpen,
    setHomeIsOpen: setHomeIsOpen,
    setExperienceIsOpen: setExperienceIsOpen,
    setProjectsIsOpen: setProjectsIsOpen,
    setHobbiesIsOpen: setHobbiesIsOpen
  }

  return (
    <ContentContext.Provider value={contentDefaultValues}>
      <div className={styles.container}>
        <Head>
          <title>George Go - Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.header}>
          <Header />
        </div>
        <div className={styles.content}>
          {homeIsOpen && 
            <div className={homeIsOpen ? 'fade_in' : ''}>
              <Intro />
            </div>
          }
          {experienceIsOpen &&
            <div className={experienceIsOpen ? 'fade_in' : ''}>
              <Experience />
            </div>
          }
          {projectsIsOpen && 
            <div className={projectsIsOpen ? 'fade_in' : ''}>
              <Projects />
            </div>
          }
          {hobbiesIsOpen && 
            <div className={hobbiesIsOpen ? 'fade_in' : ''}>
              <About />
            </div>
          }
        </div>
        <div className={styles.footer_nav}>
          <FooterNav />
        </div>
      </div>
    </ContentContext.Provider>
  )
}

export default Home
